import { ref } from "vue"

export const places = ref([
  { name: "Manila", image: "images/Manila.jpg", url: "/results?to=Manila", description: 'Manila is the vibrant capital of the Philippines, blending Spanish colonial history with modern city energy along the shores of Manila Bay. Its historic district, Intramuros, features centuries-old landmarks like Manila Cathedral and Fort Santiago. Visitors also enjoy sunset views at Rizal Park, lively street food, bustling markets, and easy access to nearby islands and cultural attractions.' },
  { name: "Ilocos Norte", image: "images/Ilocos.jpg", url: "/results?to=Ilocos+Norte", description: 'Ilocos Norte is a northern Philippine province known for dramatic coastal scenery, heritage towns, and iconic windmills along Bangui Bay. It is home to the UNESCO-listed Paoay Church and beautiful beaches in Pagudpud, often called the “Boracay of the North.” Visitors also explore historic landmarks like Cape Bojeador Lighthouse while enjoying local delicacies such as bagnet and empanada.' },
  { name: "Puerto Princesa", image: "images/Palawan.jpg", url: "/results?to=Puerto+Princesa", description: 'Puerto Princesa is a tropical gateway to Palawan, famous for its lush landscapes and crystal-clear waters. It is home to the world-renowned Puerto Princesa Subterranean River National Park, featuring one of the longest navigable underground rivers in the world. Visitors also enjoy island hopping in Honda Bay, white-sand beaches in Sabang, and fresh seafood in this eco-friendly city.' },
  { name: "Albay", image: "images/Albay.jpg", url: "/results?to=Albay", description: 'Albay is a scenic province in the Bicol Region best known for the perfectly cone-shaped Mayon Volcano. Visitors flock to landmarks like the Cagsawa Ruins for iconic views and explore nearby Legazpi City for adventure activities and local cuisine. With its dramatic landscapes and warm hospitality, Albay is a must-visit for nature lovers and thrill-seekers.' },
  { name: "Cebu", image: "images/Cebu.jpg", url: "/results?to=Cebu", description: 'Cebu is a vibrant island province blending rich Spanish-era history with world-class beaches and diving spots. In Cebu City, visitors explore iconic landmarks like Magellan\'s Cross and the Basilica del Santo Niño. Beyond the city, travelers enjoy turquoise waterfalls like Kawasan Falls and island hopping to nearby tropical paradises.' },
  { name: "Bohol", image: "images/Bohol.jpg", url: "/results?to=Bohol", description: 'Bohol is a charming island province famous for its unique natural wonders and laid-back vibe. It’s home to the iconic Chocolate Hills and the tiny Philippine tarsier, one of the world’s smallest primates. Visitors also enjoy white-sand beaches on Panglao Island, scenic Loboc River cruises, and vibrant coral reefs perfect for diving and snorkeling.' },
  { name: "Davao", image: "images/Davao.jpg", url: "/results?to=Davao", description: 'Davao City is a bustling city in Mindanao known for its clean streets, safety, and stunning natural surroundings. It is home to Mount Apo, the country’s tallest peak, and the Philippine Eagle Center, which protects the critically endangered Philippine eagle. Visitors also enjoy fresh durian, vibrant night markets, and quick trips to the white-sand beaches of nearby Samal Island.' },
  { name: "Siargao", image: "images/Siargao.jpg", url: "/results?to=Siargao", description: 'Siargao is a tropical paradise in Mindanao famous as the surfing capital of the Philippines, especially at Cloud 9. Beyond surfing, visitors can explore the stunning tidal pools at Magpupungko, swim in the emerald waters of Sugba Lagoon, and enjoy pristine beaches and island hopping adventures. Its laid-back vibe and scenic landscapes make Siargao perfect for both thrill-seekers and relaxation lovers.' }
])